to_do_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo.urls", namespace="todo")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todo/urls.py
from django.urls import path

from todo.views import (
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TaskListView,
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
    change_task_status,
)

urlpatterns = [
    path("", TaskListView.as_view(), name="task_list"),
    path("tasks/create/", TaskCreateView.as_view(), name="task_create"),
    path(
        "tasks/update/<int:pk>/", TaskUpdateView.as_view(), name="task_update"
    ),
    path(
        "tasks/delete/<int:pk>/", TaskDeleteView.as_view(), name="task_delete"
    ),
    path(
        "tasks/change_task_status/<int:pk>/",
        change_task_status,
        name="change_status",
    ),
    path("tags/", TagListView.as_view(), name="tag_list"),
    path("tags/create/", TagCreateView.as_view(), name="tag_create"),
    path("tags/update/<int:pk>/", TagUpdateView.as_view(), name="tag_update"),
    path("tags/delete/<int:pk>/", TagDeleteView.as_view(), name="tag_delete"),
]

app_name = "todo"

todo/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(blank=True, null=True)
    is_completed = models.BooleanField(default=False)
    tags = models.ManyToManyField(to=Tag, related_name="tasks")

    class Meta:
        ordering = ["is_completed", "created_at", "deadline"]

    def __str__(self):
        return f"{self.content} {self.created_at}"

todo/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views import generic

from .models import Task, Tag


class TaskListView(generic.ListView):
    model = Task


class TaskCreateView(generic.CreateView):
    model = Task
    fields = ["content", "deadline", "tags"]
    success_url = reverse_lazy("todo:task_list")


class TaskUpdateView(generic.UpdateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("todo:task_list")


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("todo:task_list")


class TagListView(generic.ListView):
    model = Tag


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo:tag_list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo:tag_list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("todo:tag_list")


def change_task_status(request, pk):
    task = Task.objects.get(id=pk)
    task.is_completed = not task.is_completed
    task.save()
    return HttpResponseRedirect(reverse_lazy("todo:task_list"))

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  {% block title %}<title>TODO</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
          crossorigin="anonymous">
</head>

<body style="margin-top: 20px;">
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">

        {% block sidebar %}
          {% include "includes/sidebar.html" %}
        {% endblock %}

      </div>
      <div class="col-sm-10 ">

        {% block content %}{% endblock %}

      </div>
    </div>
  </div>
</body>

</html>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url 'todo:task_list' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'todo:tag_list' %}">Tags</a></li>
</ul>

templates/todo/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete tag?</h1>
  <p><i>Are you sure you want to delete this tag?</i></p>

  <form action="" method="post">
    {% csrf_token %}
      <input type="submit" value="Yes, submit" class="btn btn-danger">
      <a href="{% url 'todo:tag_list' %}" class="btn btn-primary">
        Cancel
      </a>
  </form>
{% endblock %}

templates/todo/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/todo/tag_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Tags
    <a href="{% url 'todo:tag_create' %}" class="btn btn-primary link-to-page" style="float: right">
      Add
    </a>
  </h1>

  {% if tag_list %}
    <table class="table">
      <tr>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>

      {% for tag in tag_list %}
        <tr>
          <td>
              {{ tag.name }}
          </td>
          <td>
              <a href="{% url 'todo:tag_update' pk=tag.id %}" class="btn btn-secondary">
                Update
              </a>
            </td>
            <td>
              <a href="{% url 'todo:tag_delete' pk=tag.id %}" class="btn btn-secondary">
                Delete
              </a>
            </td>
        </tr>
      {% endfor %}
    </table>

  {% else %}
      <p>There are no tags!</p>
  {% endif %}
{% endblock %}

templates/todo/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete task?</h1>
  <p><i>Are you sure you want to delete this task?</i></p>

  <form action="" method="post">
    {% csrf_token %}
      <input type="submit" value="Yes, submit" class="btn btn-danger">
      <a href="{% url 'todo:task_list' %}" class="btn btn-primary">
        Cancel
      </a>
  </form>
{% endblock %}

templates/todo/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/todo/task_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    TODO list
    <a href="{% url 'todo:task_create' %}" class="btn btn-primary link-to-page">
      Add task
    </a>
  </h1><br>

  {% if task_list %}
    {% for task in task_list %}
      <p>
        <strong>
          {{ task.content }}
        </strong>
        {% if task.is_completed %}
          <strong style="color: green">
            Done
          </strong>
          <a href="{% url 'todo:change_status' pk=task.id %}" class="btn btn-secondary link-to-page">
            Undo
          </a>
        {% else %}
          <strong style="color: red">
            Not done
          </strong>
          <a href="{% url 'todo:change_status' pk=task.id %}" class="btn btn-success link-to-page">
            Complete
          </a>
        {% endif %}
      </p>
      <p style="font-size: 13px">
        Created: {{ task.created_at }}
        Deadline {{ task.deadline }}
      </p>
      <p style="color: grey; font-weight: normal">
        Tags:
        {% for tag in task.tags.all %}
          {{ tag.name }}
        {% endfor %}
        <a href="{% url 'todo:task_update' pk=task.id %}">
          Update
        </a>
        <a href="{% url 'todo:task_delete' pk=task.id %}">
          Delete
        </a>
      </p>
    {% endfor %}
  {% else %}
    <h5>No tasks to do!</h5>
  {% endif %}
{% endblock %}